#    This file is part of libaditya.
#
#    Copyright (c) 2025 Josh Harper <humanhaven@substack.com>
#
#    libaditya is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    libaditya is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with libaditya.  If not, see <https://www.gnu.org/licenses/>.

import swisseph as swe

import os

from libaditya import utils

# should be .../libaditya/libaditya
base_path = os.path.dirname(os.path.realpath(__file__))
ephe_path = base_path + "/ephe/"
stars_file = ephe_path + "sefstars.txt"
# themes are for drawing hd and sbc charts
theme_path = base_path + "/draw/themes/"
hd_default_theme = theme_path + "default-theme.hd"
sbc_default_theme = theme_path + "default-theme.sbc"

ECL = swe.FLG_TROPICAL
TROP = swe.FLG_TROPICAL
EQU = swe.FLG_EQUATORIAL
HELIO = swe.FLG_HELCTR
BARY = swe.FLG_BARYCTR
SID = swe.FLG_SIDEREAL
TOPO = swe.FLG_TOPOCTR
DRAC = -8


def sysflgstr(sflg):
    if sflg == swe.FLG_TROPICAL:
        return "Tropical"
    if sflg == swe.FLG_EQUATORIAL:
        return "Equatorial"
    if sflg == swe.FLG_HELCTR:
        return "Heliocentric"
    if sflg == swe.FLG_BARYCTR:
        return "Barycentric"
    if sflg == swe.FLG_SIDEREAL:
        return "Sidereal"
    if sflg == swe.FLG_TOPOCTR:
        return "Tropical Topocentric"
    if sflg == (swe.FLG_SIDEREAL | swe.FLG_TOPOCTR):
        return "Sidereal Topocentric"
    if sflg == DRAC:
        return "Draconic"


def ayanamsa_name(ayanamsa):
    if ayanamsa == 97:
        return "True Sidereal"
    if ayanamsa == 98:
        return "Dhruva GC mid-Mula Equatorial"
    if ayanamsa == 99:
        return "Eclitpic Vedanga Jyotisha"
    if ayanamsa == 100:
        return "Equatorial Vedanga Jyotisha"
    if ayanamsa == 101:
        return "28 Equal Nakshatras (Krittika at Equinox)"
    swe.set_sid_mode(ayanamsa)
    return swe.get_ayanamsa_name(ayanamsa)

def circle_name(circle) -> str:
    from libaditya.objects import Circle
    if circle == Circle.ADITYA:
        return "Aditya Circle"
    if circle == Circle.ZODIAC:
        return "Zodiac Circle"


# constant constants

lords = {
    1: "Mars",
    2: "Venus",
    3: "Mercury",
    4: "Moon",
    5: "Sun",
    6: "Mercury",
    7: "Venus",
    8: "Mars",
    9: "Jupiter",
    10: "Saturn",
    11: "Saturn",
    12: "Jupiter"
}

rashi_aspects = {
    "quadrant": {
        1: (2,5,8),
        2: (7,10,1),
        3: (6,9,12),
        4: (5,8,11),
        5: (10,1,4),
        6: (9,12,3),
        7: (8,11,2),
        8: (1,4,7),
        9: (12,3,6),
        10: (11,2,5),
        11: (4,7,10),
        12: (3,6,9)
    },

    "element": {
        1: (2,8,11),
        2: (7,4,1),
        3: (6,9,12),
        4: (5,2,11),
        5: (7,10,4),
        6: (9,12,3),
        7: (8,11,5),
        8: (1,10,7),
        9: (12,3,6),
        10: (11,2,8),
        11: (4,1,10),
        12: (3,6,9)
    },

    "conventional": {
        1: (5,8,11),
        2: (4,7,10),
        3: (6,9,12),
        4: (8,11,2),
        5: (7,10,1),
        6: (9,12,3),
        7: (11,2,5),
        8: (10,1,4),
        9: (12,3,6),
        10: (2,5,8),
        11: (1,4,7),
        12: (3,6,9)
    }
}

# vargas that have multiple options for them
multi_vargas = {
    "2": [2,-2],
    "3": [3,-3],
    "4": [4,-4],
    "10": [10,-10,-100],
    "16": [16,-16],
    "20": [20,-20],
    "24": [24,-24],
    "27": [27,-27],
    "40": [40,-40],
    "45": [45,-45],
    "60": [60,-60]
}

karaka_glyphs = ["⨀","☾","♂","☿","♃","♀","♄"]
graha_glyphs = ["⨀","☾","♂","☿","♃","♀","♄","☊","☋"]

# these glyphs are in order for hd
# in hd.constants, use [*glyphs.values()]
glyphs = {
    "Sun": "⨀",
    "Earth": "⨁",
    "Moon": "☾",
    "Rahu": "☊",
    "Ketu": "☋",
    "Mercury": "☿",
    "Venus": "♀",
    "Mars": "♂",
    "Jupiter": "♃",
    "Saturn": "♄",
    "Uranus": "⛢",
    "Neptune": "♆",
    "Pluto": "⯓",
    "Chiron": "⚷",
    # these are for cards of truth
    "Ecliptic": "⨁",
    "Base": "",
    "": ""
}

vimshottari_dashas = [("Ketu",7),("Venus",20),("Sun",6),("Moon",10),("Mars",7),("Rahu",18),("Jupiter",16),("Saturn",19),("Mercury",17)]

dasha_years = {
    "saura": 365.2422,
    "nakshatra": 359.0167,
    "savana": 360,
    "sidereal": 365.2564,
    "chandra": 364.2888,
    "lunar": 354.36708
}

# not sure if i use these or not; better leave them for now
nak = 13 + (1 / 3)
true_node = 11
rahu = 11
ketu = 10
earth = 12
calendardays = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
]

# used for Planet.cheshta_bala()
mean_longitude_formulas = {
    "Sun": (lambda t: (280.466449 + (36000.7698231)*t + (0.00030368)*(t**2) + (0.000000021)*(t**3))%360),
    "Mars": (lambda t: (355.433275 + (19141.6964746)*t + (0.00031097)*(t**2) + (0.000000015)*(t**3))%360),
    "Mercury": (lambda t: (252.250906 + (149474.0722491)*t + (0.00030397)*(t**2) - (0.000000018)*(t**3))%360),
    "Jupiter": (lambda t: (34.351484 + (3036.3027889)*t + (0.00022374)*(t**2) + (0.000000025)*(t**3))%360),
    "Venus": (lambda t: (181.979801 + (58519.2130302)*t + (0.00031060)*(t**2) + (0.000000015)*(t**3))%360),
    "Saturn": (lambda t: (50.07741 + (1223.5110141)*t + (0.00051952)*(t**2) - (0.000000003)*(t**3))%360)
}

signglyph = ["♈︎", "♉︎", "♊︎", "♋︎", "♌︎", "♍︎", "♎︎", "♏︎", "♐︎", "♑︎", "♒︎", "♓︎"]

# names is at the end in ruff style
# much easier to edit that way

#names = {
#    "eng":
#    {'planets': ['Sun', 'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Rahu', 'Ketu', [], [], 'Earth', 'Chiron'], 'nakshatras': ['Ashvini', 'Bharani', 'Krittika', 'Rohini', 'Mrigashira', 'Ardra', 'Punarvasu', 'Pushya', 'Ashlesha', 'Magha', 'P. Phalguni', 'U. Phalguni', 'Hasta', 'Chitra', 'Svati', 'Vishakha', 'Anuradha', 'Jyeshtha', 'Mula', 'P. Ashadha', 'U. Ashadha', 'Shravana', 'Danishtha', 'Shatabhisha', 'P. Bhadrapada', 'U. Bhadrapada', 'Revati'], 'tithis': ['nanda', 'bhadra', 'jaya', 'rikta', 'purna'], 'karanas': [['Kimtughna', 'Bava'], ['Balava', 'Kaulava'], ['Taitula', 'Garija'], ['Vanija', 'Vishti'], ['Bava', 'Balava'], ['Kaulava', 'Taitula'], ['Garija', 'Vanija'], ['Vishti', 'Bava'], ['Balava', 'Kaulava'], ['Taitula', 'Garija'], ['Vanija', 'Vishti'], ['Bava', 'Balava'], ['Kaulava', 'Taitula'], ['Garija', 'Vanija'], ['Vishti', 'Bava'], ['Balava', 'Kaulava'], ['Taitula', 'Garija'], ['Vanija', 'Vishti'], ['Bava', 'Balava'], ['Kaulava', 'Taitula'], ['Garija', 'Vanija'], ['Vishti', 'Bava'], ['Balava', 'Kaulava'], ['Taitula', 'Garija'], ['Vanija', 'Vishti'], ['Bava', 'Balava'], ['Kaulava', 'Taitula'], ['Garija', 'Vanija'], ['Vishti', 'Shakuni'], ['Chatushpada', 'Naga']], 'varas': ['Ravivara', 'Somavara', 'Mangalavara', 'Budhavara', 'Guruvara', 'Shukravara', 'Shanivara'], 'yogas': ['Vishkambha', 'Priti', 'Ayushman', 'Saubhagya', 'Shobana', 'Atiganda', 'Sukarma', 'Dhriti', 'Shoola', 'Ganda', 'Vriddhi', 'Dhruva', 'Vyaghata', 'Harshana', 'Vajra', 'Siddhi', 'Vyatipata', 'Variyan', 'Parigha', 'Shiva', 'Siddha', 'Sadhya', 'Shubha', 'Shukla', 'Brahma', 'Indra', 'Vaidhriti'], 'adityas': ['Dhata', 'Aryama', 'Mitra', 'Varuna', 'Indra', 'Vivasvan', 'Tvashta', 'Vishnu', 'Amshu', 'Bhaga', 'Pusha', 'Parjanya'], 'zodiac': ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'], "abhjit": "Abhijit"},
#    "iast":
#    {'planets': ['sūrya', 'candra', 'budha', 'śukra', 'maṅgala', 'guru', 'śani', 'brahmā', 'viṣṇu', 'śiva', 'rāhu', 'ketu', [], [], 'bhūmi', 'Chiron'], 'nakshatras': ['aśvinī', 'bharaṇī', 'kṛttikā', 'rohiṇī', 'mṛgaśīrṣa', 'ārdrā', 'punarvasu', 'puṣya', 'āśleṣā', 'maghā', 'pūrvā phalgunī', 'uttarā phalgunī', 'hasta', 'citrā', 'svāti', 'viśākhā', 'anurādhā', 'jyeṣṭhā', 'mūla', 'pūrvāṣāḍhā', 'uttarāṣāḍhā', 'śravaṇa', 'dhaniṣṭhā', 'śatabhiṣa', 'pūrvabhādrapadā', 'uttarabhādrapadā', 'revatī'], 'tithis': ['nanda', 'bhadra', 'jāya', 'ṛkta', 'pūrṇa'], 'karanas': [['kiṃtughna', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'śakuni'], ['catuṣpada', 'nāga']], 'varas': ['ravivāra', 'somavāra', 'maṅgalavāra', 'budhavāra', 'guruvāra', 'śukravāra', 'śanivāra'], 'yogas': ['viṣkambha', 'prīti', 'āyuṣmān', 'saubhāgya', 'śobhana', 'atigaṇḍa', 'sukarma', 'dhṛti', 'śula', 'gaṇḍa', 'vṛddhi', 'dhruva', 'vyāghāta', 'harṣaṇa', 'vajra', 'siddhi', 'vyātipata', 'varīyas', 'parighā', 'śiva', 'siddha', 'sādhya', 'śubha', 'śukla', 'brahmā', 'indra', 'vaidhṛti'], 'adityas': ['dhātā', 'aryamā', 'mitra', 'varuṇa', 'indra', 'vivasvān', 'tvaṣṭā', 'viṣṇu', 'aṃśu', 'bhaga', 'pūṣā', 'parjanya'], 'zodiac': ['meṣa', 'vṛṣabha', 'mithuna', 'karka', 'siṃha', 'kanyā', 'tulā', 'vṛścika', 'dhanus', 'nakra', 'kumbha', 'mīna'], "abhjit": "abhijit"},
#    "deva":
#    {'planets': ['सूर्य', 'चन्द्र', 'बुध', 'शुक्र', 'मङ्गल', 'गुरु', 'शनि', 'ब्रह्मा', 'विष्णु', 'शिव', 'राहु', 'केतु', [], [], 'भूमि', 'Chiron'], 'nakshatras': ['अश्विनी', 'भरणी', 'कृत्तिका', 'रोहिणी', 'मृगशीर्ष', 'आर्द्रा', 'पुनर्वसु', 'पुष्य', 'आश्लेषा', 'मघा', 'पूर्वा फल्गुनी', 'उत्तरा फल्गुनी', 'हस्त', 'चित्रा', 'स्वाति', 'विशाखा', 'अनुराधा', 'ज्येष्ठा', 'मूल', 'पूर्वाषाढा', 'उत्तराषाढा', 'श्रवण', 'धनिष्ठा', 'शतभिष', 'पूर्वभाद्रपदा', 'उत्तरभाद्रपदा', 'रेवती'], 'tithis': ['नन्द', 'भद्र', 'जाय', 'ऋक्त', 'पूर्ण'], 'karanas': [['किंतुघ्न', 'बव'], ['बलव', 'कौलव'], ['तैतिल', 'गरिज'], ['वणिज', 'विष्टि'], ['बव', 'बलव'], ['कौलव', 'तैतिल'], ['गरिज', 'वणिज'], ['विष्टि', 'बव'], ['बलव', 'कौलव'], ['तैतिल', 'गरिज'], ['वणिज', 'विष्टि'], ['बव', 'बलव'], ['कौलव', 'तैतिल'], ['गरिज', 'वणिज'], ['विष्टि', 'बव'], ['बलव', 'कौलव'], ['तैतिल', 'गरिज'], ['वणिज', 'विष्टि'], ['बव', 'बलव'], ['कौलव', 'तैतिल'], ['गरिज', 'वणिज'], ['विष्टि', 'बव'], ['बलव', 'कौलव'], ['तैतिल', 'गरिज'], ['वणिज', 'विष्टि'], ['बव', 'बलव'], ['कौलव', 'तैतिल'], ['गरिज', 'वणिज'], ['विष्टि', 'शकुनि'], ['चतुष्पद', 'नाग']], 'varas': ['रविवार', 'सोमवार', 'मङ्गलवार', 'बुधवार', 'गुरुवार', 'शुक्रवार', 'शनिवार'], 'yogas': ['विष्कम्भ', 'प्रीति', 'आयुष्मान्', 'सौभाग्य', 'शोभन', 'अतिगण्ड', 'सुकर्म', 'धृति', 'शुल', 'गण्ड', 'वृद्धि', 'ध्रुव', 'व्याघात', 'हर्षण', 'वज्र', 'सिद्धि', 'व्यातिपत', 'वरीयस्', 'परिघा', 'शिव', 'सिद्ध', 'साध्य', 'शुभ', 'शुक्ल', 'ब्रह्मा', 'इन्द्र', 'वैधृति'], 'adityas': ['धाता', 'अर्यमा', 'मित्र', 'वरुण', 'इन्द्र', 'विवस्वान्', 'त्वष्टा', 'विष्णु', 'अंशु', 'भग', 'पूषा', 'पर्जन्य'], 'zodiac': ['मेष', 'वृषभ', 'मिथुन', 'कर्क', 'सिंह', 'कन्या', 'तुला', 'वृश्चिक', 'धनुस्', 'नक्र', 'कुम्भ', 'मी
#    "mixed":
#    {'planets': ['Sun', 'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Rahu', 'Ketu', [], [], 'Earth', 'Chiron'], 'nakshatras': ['aśvinī', 'bharaṇī', 'kṛttikā', 'rohiṇī', 'mṛgaśīrṣa', 'ārdrā', 'punarvasu', 'puṣya', 'āśleṣā', 'maghā', 'pūrvā phalgunī', 'uttarā phalgunī', 'hasta', 'citrā', 'svāti', 'viśākhā', 'anurādhā', 'jyeṣṭhā', 'mūla', 'pūrvāṣāḍhā', 'uttarāṣāḍhā', 'śravaṇa', 'dhaniṣṭhā', 'śatabhiṣa', 'pūrvabhādrapadā', 'uttarabhādrapadā', 'revatī'], 'tithis': ['nanda', 'bhadra', 'jāya', 'ṛkta', 'pūrṇa'], 'karanas': [['kiṃtughna', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'bava'], ['balava', 'kaulava'], ['taitila', 'garija'], ['vaṇija', 'viṣṭi'], ['bava', 'balava'], ['kaulava', 'taitila'], ['garija', 'vaṇija'], ['viṣṭi', 'śakuni'], ['catuṣpada', 'nāga']], 'varas': ['ravivāra', 'somavāra', 'maṅgalavāra', 'budhavāra', 'guruvāra', 'śukravāra', 'śanivāra'], 'yogas': ['viṣkambha', 'prīti', 'āyuṣmān', 'saubhāgya', 'śobhana', 'atigaṇḍa', 'sukarma', 'dhṛti', 'śula', 'gaṇḍa', 'vṛddhi', 'dhruva', 'vyāghāta', 'harṣaṇa', 'vajra', 'siddhi', 'vyātipata', 'varīyas', 'parighā', 'śiva', 'siddha', 'sādhya', 'śubha', 'śukla', 'brahmā', 'indra', 'vaidhṛti'], 'adityas': ['dhātā', 'aryamā', 'mitra', 'varuṇa', 'indra', 'vivasvān', 'tvaṣṭā', 'viṣṇu', 'aṃśu', 'bhaga', 'pūṣā', 'parjanya'], 'zodiac': ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'], "abhijit": "abhijit"},
#    "abbrev":
#    {'planets': ['Su', 'Mo', 'Me', 'Ve', 'Ma', 'Ju', 'Sa', 'Ur', 'Ne', 'Pl', 'Ra', 'Ke', [], [], 'Ea', 'Ch'], 'nakshatras': ['aśv', 'bha', 'kṛt', 'roh', 'mṛg', 'ārd', 'pun', 'puṣ', 'āśl', 'mag', 'pph', 'uph', 'has', 'cit', 'svā', 'viś', 'anu', 'jye', 'mūl', 'pāṣ', 'uāṣ', 'śra', 'dha', 'śat', 'pdā', 'udā', 'rev'], 'tithis': ['nan', 'bha', 'jāy', 'ṛkt', 'pūr'], 'karanas': [['kiṃ', 'bav'], ['bal', 'kau'], ['tai', 'gar'], ['vaṇ', 'viṣ'], ['bav', 'bal'], ['kau', 'tai'], ['gar', 'vaṇ'], ['viṣ', 'bav'], ['bal', 'kau'], ['tai', 'gar'], ['vaṇ', 'viṣ'], ['bav', 'bal'], ['kau', 'tai'], ['gar', 'vaṇ'], ['viṣ', 'bav'], ['bal', 'kau'], ['tai', 'gar'], ['vaṇ', 'viṣ'], ['bav', 'bal'], ['kau', 'tai'], ['gar', 'vaṇ'], ['viṣ', 'bav'], ['bal', 'kau'], ['tai', 'gar'], ['vaṇ', 'viṣ'], ['bav', 'bal'], ['kau', 'tai'], ['gar', 'vaṇ'], ['viṣ', 'śak'], ['cat', 'nāg']], 'varas': ['rav', 'som', 'maṅ', 'bud', 'gur', 'śuk', 'śan'], 'yogas': ['viṣ', 'prī', 'āyu', 'sau', 'śob', 'ati', 'suk', 'dhṛ', 'śul', 'gaṇ', 'vṛd', 'dhr', 'vyā', 'har', 'vaj', 'sid', 'vyā', 'var', 'par', 'śiv', 'sid', 'sād', 'śub', 'śuk', 'bra', 'ind', 'vai'], 'adityas': ['dhā', 'ary', 'mit', 'var', 'ind', 'viv', 'tva', 'viṣ', 'aṃś', 'bha', 'pūṣ', 'par'], 'zodiac': ['Ar', 'Ta', 'Ge', 'Ca', 'Le', 'Vi', 'Li', 'Sc', 'Sa', 'Ca', 'Aq', 'Pi'], "abhijit": "ab"},
#}
#
planet_names = [
    "Sun",
    "Moon",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Rahu",
    "Ketu",
    [],
    [],
    "Earth",
    "Chiron",
]

planet_names_abbreviated = [
    "Su",
    "Mo",
    "Me",
    "Ve",
    "Ma",
    "Ju",
    "Sa",
    "Ur",
    "Ne",
    "Pl",
    "Ra",
    "Ke",
    [],
    [],
    "Ea",
    "Ch",
]

zodiac = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
]
zodiac_abbreviated = [
    "Ar",
    "Ta",
    "Ge",
    "Ca",
    "Le",
    "Vi",
    "Li",
    "Sc",
    "Sa",
    "Ca",
    "Aq",
    "Pi",
]

tithis = ["nanda", "bhadra", "jāya", "ṛkta", "pūrṇa"]

tithis_abbreviated = ["nan", "bha", "jāy", "ṛkt", "pūr"]

karanas = [
    ["kiṃtughna", "bava"],
    ["balava", "kaulava"],
    ["taitila", "garija"],
    ["vaṇija", "viṣṭi"],
    ["bava", "balava"],
    ["kaulava", "taitila"],
    ["garija", "vaṇija"],
    ["viṣṭi", "bava"],
    ["balava", "kaulava"],
    ["taitila", "garija"],
    ["vaṇija", "viṣṭi"],
    ["bava", "balava"],
    ["kaulava", "taitila"],
    ["garija", "vaṇija"],
    ["viṣṭi", "bava"],
    ["balava", "kaulava"],
    ["taitila", "garija"],
    ["vaṇija", "viṣṭi"],
    ["bava", "balava"],
    ["kaulava", "taitila"],
    ["garija", "vaṇija"],
    ["viṣṭi", "bava"],
    ["balava", "kaulava"],
    ["taitila", "garija"],
    ["vaṇija", "viṣṭi"],
    ["bava", "balava"],
    ["kaulava", "taitila"],
    ["garija", "vaṇija"],
    ["viṣṭi", "śakuni"],
    ["catuṣpada", "nāga"],
]

karanas_abbreviated = [
    ["kiṃ", "bav"],
    ["bal", "kau"],
    ["tai", "gar"],
    ["vaṇ", "viṣ"],
    ["bav", "bal"],
    ["kau", "tai"],
    ["gar", "vaṇ"],
    ["viṣ", "bav"],
    ["bal", "kau"],
    ["tai", "gar"],
    ["vaṇ", "viṣ"],
    ["bav", "bal"],
    ["kau", "tai"],
    ["gar", "vaṇ"],
    ["viṣ", "bav"],
    ["bal", "kau"],
    ["tai", "gar"],
    ["vaṇ", "viṣ"],
    ["bav", "bal"],
    ["kau", "tai"],
    ["gar", "vaṇ"],
    ["viṣ", "bav"],
    ["bal", "kau"],
    ["tai", "gar"],
    ["vaṇ", "viṣ"],
    ["bav", "bal"],
    ["kau", "tai"],
    ["gar", "vaṇ"],
    ["viṣ", "śak"],
    ["cat", "nāg"],
]

nakshatras = [
    "aśvinī",
    "bharaṇī",
    "kṛttikā",
    "rohiṇī",
    "mṛgaśīrṣa",
    "ārdrā",
    "punarvasu",
    "puṣya",
    "āśleṣā",
    "maghā",
    "pūrvā phalgunī",
    "uttarā phalgunī",
    "hasta",
    "citrā",
    "svāti",
    "viśākhā",
    "anurādhā",
    "jyeṣṭhā",
    "mūla",
    "pūrvāṣāḍhā",
    "uttarāṣāḍhā",
    "śravaṇa",
    "dhaniṣṭhā",
    "śatabhiṣa",
    "pūrvabhādrapadā",
    "uttarabhādrapadā",
    "revatī",
]

nakshatras_abbreviated = [
    "aśv",
    "bha",
    "kṛt",
    "roh",
    "mṛg",
    "ārd",
    "pun",
    "puṣ",
    "āśl",
    "mag",
    "pph",
    "uph",
    "has",
    "cit",
    "svā",
    "viś",
    "anu",
    "jye",
    "mūl",
    "pāṣ",
    "uāṣ",
    "śra",
    "dha",
    "śat",
    "pdā",
    "udā",
    "rev",
]

varas = [
    "ravivāra",
    "somavāra",
    "maṅgalavāra",
    "budhavāra",
    "guruvāra",
    "śukravāra",
    "śanivāra",
]

varas_abbreviated = [
    "rav",
    "som",
    "maṅ",
    "bud",
    "gur",
    "śuk",
    "śan",
]

yogas = [
    "viṣkambha",
    "prīti",
    "āyuṣmān",
    "saubhāgya",
    "śobhana",
    "atigaṇḍa",
    "sukarma",
    "dhṛti",
    "śula",
    "gaṇḍa",
    "vṛddhi",
    "dhruva",
    "vyāghāta",
    "harṣaṇa",
    "vajra",
    "siddhi",
    "vyātipata",
    "varīyas",
    "parighā",
    "śiva",
    "siddha",
    "sādhya",
    "śubha",
    "śukla",
    "brahmā",
    "indra",
    "vaidhṛti",
]

yogas_abbreviated = [
    "viṣ",
    "prī",
    "āyu",
    "sau",
    "śob",
    "ati",
    "suk",
    "dhṛ",
    "śul",
    "gaṇ",
    "vṛd",
    "dhr",
    "vyā",
    "har",
    "vaj",
    "sid",
    "vyā",
    "var",
    "par",
    "śiv",
    "sid",
    "sād",
    "śub",
    "śuk",
    "bra",
    "ind",
    "vai",
]

adityas = [
    "dhātā",
    "aryamā",
    "mitra",
    "varuṇa",
    "indra",
    "vivasvān",
    "tvaṣṭā",
    "viṣṇu",
    "aṃśu",
    "bhaga",
    "pūṣā",
    "parjanya",
]

adityas_abbreviated = [
    "dhā",
    "ary",
    "mit",
    "var",
    "ind",
    "viv",
    "tva",
    "viṣ",
    "aṃś",
    "bha",
    "pūṣ",
    "par",
]

sign_names = adityas
sign_names_abbreviated = adityas_abbreviated

abbreviated_names = planet_names_abbreviated,sign_names_abbreviated,nakshatras_abbreviated,tithis_abbreviated,karanas_abbreviated,varas_abbreviated,yogas_abbreviated


varga_deities={
    2: ["Sun", "Moon"],
    3: ["Narada", "Agastya", "Durvasas"],
    4: ["Sanaka", "Sananda", "Sanatkumāra", "Sanātana"],
    7: ["Kshara", "Kshira", "Dadhya", "Ajya", "Ikshurasa", "Madhya", "Shuddha Jala"],
    9: ["Deva","Nri","Rakshasa"],
    10: ["Indra","Agni","Yama","Rakshasa","Varuna","Vayu","Kubera","Ishana","Brahma","Ananta"],
    12: ["Ganesha", "Ashvins", "Yama", "Hayagriva"],
    16: ["Brahma", "Vishnu", "Shiva", "Sun"],
    20: ["Daya", "Megha", "Chinnashirsha", "Pishachani", "Dhumavati", "Matangi", "Bala", "Bhadra", "Aruna", "Anala", "Pingala", "Chucchuka", "Ghora", "Varahi", "Vaishnavi", "Sita", "Bhuvanesvari", "Bhairavi", "Mangala", "Aparajita"],
    # 21 is for odd signs in the -20/20
    21: ["Kali", "Gauri", "Jaya", "Lakshmi", "Vijaya", "Vimala", "Sati", "Tara", "Jvalamukhi", "Shveta", "Lalita", "Bagalamukhi", "Pratyangira", "Sachi", "Raudri", "Bhavani", "Varada", "Jaya", "Tripura", "Sumukhi"],
    24: ["Skanda", "Parsudhara", "Anala", "Vishwakarma", "Bhaga", "Mitra", "Maya", "Antaka", "Vrishadhwaja", "Govinda", "Madana", "Bhima"],
    27: ["Dastra", "Yama", "Agni", "Pitamaha", "Chandra", "Isha", "Aditi", "Jiva", "Ahi", "Pitara", "Bhaga", "Aryama", "Arka", "Tvashta", "Marut", "Shakragni", "Mitra", "Vasava", "Nirriti", "Varuna", "Vishvadeva", "Govinda", "Vasu", "Varuna", "Ajapa", "Ahirbudhanya", "Pusha"],
    40: ["Vishnu", "Chandra", "Marichi", "Tvashta", "Dhata", "Shiva", "Ravi", "Yama", "Yaksha", "Gandharva", "Kala", "Varuna"],
    45: ["Vidhi", "Isha", "Acyuta"],
    # for -45 fixed signs
    46: ["Isha", "Acyuta", "Surajyeshta"],
    # for -45 dual signs
    47: ["Vishnu", "Ka", "Isha"],
    60: ["Ghora", "Rakshasa", "Deva", "Kubera", "Yaksha", "Kimnara", "Bhrashta", "Kulaghna", "Garala", "Vahni", "Maya", "Purishaka", "Apampathi", "Marut", "Kala", "Sarpa", "Amrita", "Indu", "Mridu", "Komala", "Heramba", "Brahma", "Vishnu", "Maheshwara", "Deva", "Ardra", "Kalinasha", "Kshitisha", "Kamalakara", "Gulika", "Mrityu", "Kala", "Davagni", "Ghora", "Yama", "Kantaka", "Sudha", "Amrita", "Purnachandra", "Vishadaghda", "Kulanasa", "Vamsakshaya", "Utpata", "Kala", "Saumya", "Komala", "Sitala", "Karaladamshtra", "Chandramukhi", "Pravina", "Kala Pavaka", "Dandayudha", "Nirmala", "Saumya", "Krura", "Atisitala", "Amrita", "Payodhi", "Bhramana", "Chandra Rekha"]
}

# used for pyhd and sbc themes
# just initializes a dictionary
# i guess it could be a .toml file?
# this is same thing
def init_theme(file=None):
    input = open(file,'r')
    
    config = {} # empty dictionary

    for line in input:
       if not "=" in line or line.startswith('#'):
           continue # either a comment or not a variable if line doesnt have =
       field, value = line.split("=")
       field = field.strip().lower()
       value = value.strip()
       config[field]=value 
    input.close()
    return config

# template comment box

########################################################
#                                                      #
#                                                      #
#                                                      #
#                                                      #
#                                                      #
########################################################


names = {
    "eng": {
        "planets": [
            "Sun",
            "Moon",
            "Mercury",
            "Venus",
            "Mars",
            "Jupiter",
            "Saturn",
            "Uranus",
            "Neptune",
            "Pluto",
            "Rahu",
            "Ketu",
            [],
            [],
            "Earth",
            "Chiron",
        ],
        "nakshatras": [
            "Ashvini",
            "Bharani",
            "Krittika",
            "Rohini",
            "Mrigashira",
            "Ardra",
            "Punarvasu",
            "Pushya",
            "Ashlesha",
            "Magha",
            "P. Phalguni",
            "U. Phalguni",
            "Hasta",
            "Chitra",
            "Svati",
            "Vishakha",
            "Anuradha",
            "Jyeshtha",
            "Mula",
            "P. Ashadha",
            "U. Ashadha",
            "Shravana",
            "Danishtha",
            "Shatabhisha",
            "P. Bhadrapada",
            "U. Bhadrapada",
            "Revati",
        ],
        "nakshatras_28eq": [
            "Krittika",
            "Rohini",
            "Mrigashira",
            "Ardra",
            "Punarvasu",
            "Pushya",
            "Ashlesha",
            "Magha",
            "P. Phalguni",
            "U. Phalguni",
            "Hasta",
            "Chitra",
            "Svati",
            "Vishakha",
            "Anuradha",
            "Jyeshtha",
            "Mula",
            "P. Ashadha",
            "U. Ashadha",
            "Abhijit",
            "Shravana",
            "Danishtha",
            "Shatabhisha",
            "P. Bhadrapada",
            "U. Bhadrapada",
            "Revati",
            "Ashvini",
            "Bharani",
        ],
        "tithis": ["nanda", "bhadra", "jaya", "rikta", "purna"],
        "karanas": [
            ["Kimtughna", "Bava"],
            ["Balava", "Kaulava"],
            ["Taitula", "Garija"],
            ["Vanija", "Vishti"],
            ["Bava", "Balava"],
            ["Kaulava", "Taitula"],
            ["Garija", "Vanija"],
            ["Vishti", "Bava"],
            ["Balava", "Kaulava"],
            ["Taitula", "Garija"],
            ["Vanija", "Vishti"],
            ["Bava", "Balava"],
            ["Kaulava", "Taitula"],
            ["Garija", "Vanija"],
            ["Vishti", "Bava"],
            ["Balava", "Kaulava"],
            ["Taitula", "Garija"],
            ["Vanija", "Vishti"],
            ["Bava", "Balava"],
            ["Kaulava", "Taitula"],
            ["Garija", "Vanija"],
            ["Vishti", "Bava"],
            ["Balava", "Kaulava"],
            ["Taitula", "Garija"],
            ["Vanija", "Vishti"],
            ["Bava", "Balava"],
            ["Kaulava", "Taitula"],
            ["Garija", "Vanija"],
            ["Vishti", "Shakuni"],
            ["Chatushpada", "Naga"],
        ],
        "varas": [
            "Ravivara",
            "Somavara",
            "Mangalavara",
            "Budhavara",
            "Guruvara",
            "Shukravara",
            "Shanivara",
        ],
        "yogas": [
            "Vishkambha",
            "Priti",
            "Ayushman",
            "Saubhagya",
            "Shobana",
            "Atiganda",
            "Sukarma",
            "Dhriti",
            "Shoola",
            "Ganda",
            "Vriddhi",
            "Dhruva",
            "Vyaghata",
            "Harshana",
            "Vajra",
            "Siddhi",
            "Vyatipata",
            "Variyan",
            "Parigha",
            "Shiva",
            "Siddha",
            "Sadhya",
            "Shubha",
            "Shukla",
            "Brahma",
            "Indra",
            "Vaidhriti",
        ],
        "adityas": [
            "Dhata",
            "Aryama",
            "Mitra",
            "Varuna",
            "Indra",
            "Vivasvan",
            "Tvashta",
            "Vishnu",
            "Amshu",
            "Bhaga",
            "Pusha",
            "Parjanya",
        ],
        "zodiac": [
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Capricorn",
            "Aquarius",
            "Pisces",
        ],
        "abhijit":
        "Abhijit",
        "ophiucus":
        "Ophiucus"
    },
    "iast": {
        "planets": [
            "sūrya",
            "candra",
            "budha",
            "śukra",
            "maṅgala",
            "guru",
            "śani",
            "brahmā",
            "viṣṇu",
            "śiva",
            "rāhu",
            "ketu",
            [],
            [],
            "bhūmi",
            "Chiron",
        ],
        "nakshatras": [
            "aśvinī",
            "bharaṇī",
            "kṛttikā",
            "rohiṇī",
            "mṛgaśīrṣa",
            "ārdrā",
            "punarvasu",
            "puṣya",
            "āśleṣā",
            "maghā",
            "pūrvā phalgunī",
            "uttarā phalgunī",
            "hasta",
            "citrā",
            "svāti",
            "viśākhā",
            "anurādhā",
            "jyeṣṭhā",
            "mūla",
            "pūrvāṣāḍhā",
            "uttarāṣāḍhā",
            "śravaṇa",
            "dhaniṣṭhā",
            "śatabhiṣa",
            "pūrvabhādrapadā",
            "uttarabhādrapadā",
            "revatī",
        ],
        "nakshatras_28eq": [
            "kṛttikā",
            "rohiṇī",
            "mṛgaśīrṣa",
            "ārdrā",
            "punarvasu",
            "puṣya",
            "āśleṣā",
            "maghā",
            "pūrvā phalgunī",
            "uttarā phalgunī",
            "hasta",
            "citrā",
            "svāti",
            "viśākhā",
            "anurādhā",
            "jyeṣṭhā",
            "mūla",
            "pūrvāṣāḍhā",
            "uttarāṣāḍhā",
            "abhijit",
            "śravaṇa",
            "dhaniṣṭhā",
            "śatabhiṣa",
            "pūrvabhādrapadā",
            "uttarabhādrapadā",
            "revatī",
            "aśvinī",
            "bharaṇī",
        ],
        "tithis": ["nanda", "bhadra", "jāya", "ṛkta", "pūrṇa"],
        "karanas": [
            ["kiṃtughna", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "śakuni"],
            ["catuṣpada", "nāga"],
        ],
        "varas": [
            "ravivāra",
            "somavāra",
            "maṅgalavāra",
            "budhavāra",
            "guruvāra",
            "śukravāra",
            "śanivāra",
        ],
        "yogas": [
            "viṣkambha",
            "prīti",
            "āyuṣmān",
            "saubhāgya",
            "śobhana",
            "atigaṇḍa",
            "sukarma",
            "dhṛti",
            "śula",
            "gaṇḍa",
            "vṛddhi",
            "dhruva",
            "vyāghāta",
            "harṣaṇa",
            "vajra",
            "siddhi",
            "vyātipata",
            "varīyas",
            "parighā",
            "śiva",
            "siddha",
            "sādhya",
            "śubha",
            "śukla",
            "brahmā",
            "indra",
            "vaidhṛti",
        ],
        "adityas": [
            "dhātā",
            "aryamā",
            "mitra",
            "varuṇa",
            "indra",
            "vivasvān",
            "tvaṣṭā",
            "viṣṇu",
            "aṃśu",
            "bhaga",
            "pūṣā",
            "parjanya",
        ],
        "zodiac": [
            "meṣa",
            "vṛṣabha",
            "mithuna",
            "karka",
            "siṃha",
            "kanyā",
            "tulā",
            "vṛścika",
            "dhanus",
            "nakra",
            "kumbha",
            "mīna",
        ],
        "abhijit":
        "abhijit",
    },
    "deva": {
        "planets": [
            "सूर्य",
            "चन्द्र",
            "बुध",
            "शुक्र",
            "मङ्गल",
            "गुरु",
            "शनि",
            "ब्रह्मा",
            "विष्णु",
            "शिव",
            "राहु",
            "केतु",
            [],
            [],
            "भूमि",
            "Chiron",
        ],
        "nakshatras": [
            "अश्विनी",
            "भरणी",
            "कृत्तिका",
            "रोहिणी",
            "मृगशीर्ष",
            "आर्द्रा",
            "पुनर्वसु",
            "पुष्य",
            "आश्लेषा",
            "मघा",
            "पूर्वा फल्गुनी",
            "उत्तरा फल्गुनी",
            "हस्त",
            "चित्रा",
            "स्वाति",
            "विशाखा",
            "अनुराधा",
            "ज्येष्ठा",
            "मूल",
            "पूर्वाषाढा",
            "उत्तराषाढा",
            "श्रवण",
            "धनिष्ठा",
            "शतभिष",
            "पूर्वभाद्रपदा",
            "उत्तरभाद्रपदा",
            "रेवती",
        ],
        "nakshatras_28eq": [
            "कृत्तिका",
            "रोहिणी",
            "मृगशीर्ष",
            "आर्द्रा",
            "पुनर्वसु",
            "पुष्य",
            "आश्लेषा",
            "मघा",
            "पूर्वा फल्गुनी",
            "उत्तरा फल्गुनी",
            "हस्त",
            "चित्रा",
            "स्वाति",
            "विशाखा",
            "अनुराधा",
            "ज्येष्ठा",
            "मूल",
            "पूर्वाषाढा",
            "उत्तराषाढा",
            "अभिजित्",
            "श्रवण",
            "धनिष्ठा",
            "शतभिष",
            "पूर्वभाद्रपदा",
            "उत्तरभाद्रपदा",
            "रेवती",
            "अश्विनी",
            "भरणी",
        ],
        "tithis": ["नन्द", "भद्र", "जाय", "ऋक्त", "पूर्ण"],
        "karanas": [
            ["किंतुघ्न", "बव"],
            ["बलव", "कौलव"],
            ["तैतिल", "गरिज"],
            ["वणिज", "विष्टि"],
            ["बव", "बलव"],
            ["कौलव", "तैतिल"],
            ["गरिज", "वणिज"],
            ["विष्टि", "बव"],
            ["बलव", "कौलव"],
            ["तैतिल", "गरिज"],
            ["वणिज", "विष्टि"],
            ["बव", "बलव"],
            ["कौलव", "तैतिल"],
            ["गरिज", "वणिज"],
            ["विष्टि", "बव"],
            ["बलव", "कौलव"],
            ["तैतिल", "गरिज"],
            ["वणिज", "विष्टि"],
            ["बव", "बलव"],
            ["कौलव", "तैतिल"],
            ["गरिज", "वणिज"],
            ["विष्टि", "बव"],
            ["बलव", "कौलव"],
            ["तैतिल", "गरिज"],
            ["वणिज", "विष्टि"],
            ["बव", "बलव"],
            ["कौलव", "तैतिल"],
            ["गरिज", "वणिज"],
            ["विष्टि", "शकुनि"],
            ["चतुष्पद", "नाग"],
        ],
        "varas": ["रविवार", "सोमवार", "मङ्गलवार", "बुधवार", "गुरुवार", "शुक्रवार", "शनिवार"],
        "yogas": [
            "विष्कम्भ",
            "प्रीति",
            "आयुष्मान्",
            "सौभाग्य",
            "शोभन",
            "अतिगण्ड",
            "सुकर्म",
            "धृति",
            "शुल",
            "गण्ड",
            "वृद्धि",
            "ध्रुव",
            "व्याघात",
            "हर्षण",
            "वज्र",
            "सिद्धि",
            "व्यातिपत",
            "वरीयस्",
            "परिघा",
            "शिव",
            "सिद्ध",
            "साध्य",
            "शुभ",
            "शुक्ल",
            "ब्रह्मा",
            "इन्द्र",
            "वैधृति",
        ],
        "adityas": [
            "धाता",
            "अर्यमा",
            "मित्र",
            "वरुण",
            "इन्द्र",
            "विवस्वान्",
            "त्वष्टा",
            "विष्णु",
            "अंशु",
            "भग",
            "पूषा",
            "पर्जन्य",
        ],
        "zodiac": [
            "मेष",
            "वृषभ",
            "मिथुन",
            "कर्क",
            "सिंह",
            "कन्या",
            "तुला",
            "वृश्चिक",
            "धनुस्",
            "नक्र",
            "कुम्भ",
            "मीन",
        ],
        "abhijit":
            "अभिजित्"
    },
    "mixed": {
        "planets": [
            "Sun",
            "Moon",
            "Mercury",
            "Venus",
            "Mars",
            "Jupiter",
            "Saturn",
            "Uranus",
            "Neptune",
            "Pluto",
            "Rahu",
            "Ketu",
            [],
            [],
            "Earth",
            "Chiron",
        ],
        "nakshatras": [
            "aśvinī",
            "bharaṇī",
            "kṛttikā",
            "rohiṇī",
            "mṛgaśīrṣa",
            "ārdrā",
            "punarvasu",
            "puṣya",
            "āśleṣā",
            "maghā",
            "pūrvā phalgunī",
            "uttarā phalgunī",
            "hasta",
            "citrā",
            "svāti",
            "viśākhā",
            "anurādhā",
            "jyeṣṭhā",
            "mūla",
            "pūrvāṣāḍhā",
            "uttarāṣāḍhā",
            "śravaṇa",
            "dhaniṣṭhā",
            "śatabhiṣa",
            "pūrvabhādrapadā",
            "uttarabhādrapadā",
            "revatī",
        ],
        "nakshatras_28eq": [
            "kṛttikā",
            "rohiṇī",
            "mṛgaśīrṣa",
            "ārdrā",
            "punarvasu",
            "puṣya",
            "āśleṣā",
            "maghā",
            "pūrvā phalgunī",
            "uttarā phalgunī",
            "hasta",
            "citrā",
            "svāti",
            "viśākhā",
            "anurādhā",
            "jyeṣṭhā",
            "mūla",
            "pūrvāṣāḍhā",
            "uttarāṣāḍhā",
            "abhijit",
            "śravaṇa",
            "dhaniṣṭhā",
            "śatabhiṣa",
            "pūrvabhādrapadā",
            "uttarabhādrapadā",
            "revatī",
            "aśvinī",
            "bharaṇī",
        ],
        "tithis": ["nanda", "bhadra", "jāya", "ṛkta", "pūrṇa"],
        "karanas": [
            ["kiṃtughna", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "bava"],
            ["balava", "kaulava"],
            ["taitila", "garija"],
            ["vaṇija", "viṣṭi"],
            ["bava", "balava"],
            ["kaulava", "taitila"],
            ["garija", "vaṇija"],
            ["viṣṭi", "śakuni"],
            ["catuṣpada", "nāga"],
        ],
        "varas": [
            "ravivāra",
            "somavāra",
            "maṅgalavāra",
            "budhavāra",
            "guruvāra",
            "śukravāra",
            "śanivāra",
        ],
        "yogas": [
            "viṣkambha",
            "prīti",
            "āyuṣmān",
            "saubhāgya",
            "śobhana",
            "atigaṇḍa",
            "sukarma",
            "dhṛti",
            "śula",
            "gaṇḍa",
            "vṛddhi",
            "dhruva",
            "vyāghāta",
            "harṣaṇa",
            "vajra",
            "siddhi",
            "vyātipata",
            "varīyas",
            "parighā",
            "śiva",
            "siddha",
            "sādhya",
            "śubha",
            "śukla",
            "brahmā",
            "indra",
            "vaidhṛti",
        ],
        "adityas": [
            "dhātā",
            "aryamā",
            "mitra",
            "varuṇa",
            "indra",
            "vivasvān",
            "tvaṣṭā",
            "viṣṇu",
            "aṃśu",
            "bhaga",
            "pūṣā",
            "parjanya",
        ],
        "zodiac": [
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Capricorn",
            "Aquarius",
            "Pisces",
        ],
        "abhijit":
        "abhijit",
    },
    "abbrev": {
        "planets": [
            "Su",
            "Mo",
            "Me",
            "Ve",
            "Ma",
            "Ju",
            "Sa",
            "Ur",
            "Ne",
            "Pl",
            "Ra",
            "Ke",
            [],
            [],
            "Ea",
            "Ch",
        ],
        "nakshatras": [
            "aśv",
            "bha",
            "kṛt",
            "roh",
            "mṛg",
            "ārd",
            "pun",
            "puṣ",
            "āśl",
            "mag",
            "pph",
            "uph",
            "has",
            "cit",
            "svā",
            "viś",
            "anu",
            "jye",
            "mūl",
            "pāṣ",
            "uāṣ",
            "śra",
            "dha",
            "śat",
            "pdā",
            "udā",
            "rev",
        ],
        "nakshatras_28eq": [
            "kṛt",
            "roh",
            "mṛg",
            "ārd",
            "pun",
            "puṣ",
            "āśl",
            "mag",
            "pph",
            "uph",
            "has",
            "cit",
            "svā",
            "viś",
            "anu",
            "jye",
            "mūl",
            "pāṣ",
            "uāṣ",
            "abh",
            "śra",
            "dha",
            "śat",
            "pdā",
            "udā",
            "rev",
            "aśv",
            "bha",
        ],
        "tithis": ["nan", "bha", "jāy", "ṛkt", "pūr"],
        "karanas": [
            ["kiṃ", "bav"],
            ["bal", "kau"],
            ["tai", "gar"],
            ["vaṇ", "viṣ"],
            ["bav", "bal"],
            ["kau", "tai"],
            ["gar", "vaṇ"],
            ["viṣ", "bav"],
            ["bal", "kau"],
            ["tai", "gar"],
            ["vaṇ", "viṣ"],
            ["bav", "bal"],
            ["kau", "tai"],
            ["gar", "vaṇ"],
            ["viṣ", "bav"],
            ["bal", "kau"],
            ["tai", "gar"],
            ["vaṇ", "viṣ"],
            ["bav", "bal"],
            ["kau", "tai"],
            ["gar", "vaṇ"],
            ["viṣ", "bav"],
            ["bal", "kau"],
            ["tai", "gar"],
            ["vaṇ", "viṣ"],
            ["bav", "bal"],
            ["kau", "tai"],
            ["gar", "vaṇ"],
            ["viṣ", "śak"],
            ["cat", "nāg"],
        ],
        "varas": ["rav", "som", "maṅ", "bud", "gur", "śuk", "śan"],
        "yogas": [
            "viṣ",
            "prī",
            "āyu",
            "sau",
            "śob",
            "ati",
            "suk",
            "dhṛ",
            "śul",
            "gaṇ",
            "vṛd",
            "dhr",
            "vyā",
            "har",
            "vaj",
            "sid",
            "vyā",
            "var",
            "par",
            "śiv",
            "sid",
            "sād",
            "śub",
            "śuk",
            "bra",
            "ind",
            "vai",
        ],
        "adityas": [
            "dhā",
            "ary",
            "mit",
            "var",
            "ind",
            "viv",
            "tva",
            "viṣ",
            "aṃś",
            "bha",
            "pūṣ",
            "par",
        ],
        "zodiac": [
            "Ar",
            "Ta",
            "Ge",
            "Ca",
            "Le",
            "Vi",
            "Li",
            "Sc",
            "Sa",
            "Ca",
            "Aq",
            "Pi",
        ],
        "abhijit":
        "abh",
    },
}

greek_alphabet_internet_original = {
    'Alpha': u'\u0391' ,
    'Beta': u'\u0392',
    'Gamma': u'\u0393',
    'Delta': u'\u0394',
    'Epsilon': u'\u0395',
    'Zeta': u'\u0396',
    'Eta': u'\u0397',
    'Theta': u'\u0398',
    'Iota': u'\u0399',
    'Kappa': u'\u039A',
    'Lamda': u'\u039B',
    'Mu': u'\u039C',
    'Nu': u'\u039D',
    'Xi': u'\u039E',
    'Omicron': u'\u039F',
    'Pi': u'\u03A0',
    'Rho': u'\u03A1',
    'Sigma': u'\u03A3',
    'Tau': u'\u03A4',
    'Upsilon': u'\u03A5',
    'Phi': u'\u03A6',
    'Chi': u'\u03A7',
    'Psi': u'\u03A8',
    'Omega': u'\u03A9',
    'alpha': u'\u03B1',
    'beta': u'\u03B2',
    'gamma': u'\u03B3',
    'delta': u'\u03B4',
    'epsilon': u'\u03B5',
    'zeta': u'\u03B6',
    'eta': u'\u03B7',
    'theta': u'\u03B8',
    'iota': u'\u03B9',
    'kappa': u'\u03BA',
    'lamda': u'\u03BB',
    'mu': u'\u03BC',
    'nu': u'\u03BD',
    'xi': u'\u03BE',
    'omicron': u'\u03BF',
    'pi': u'\u03C0',
    'rho': u'\u03C1',
    'sigma': u'\u03C3',
    'tau': u'\u03C4',
    'upsilon': u'\u03C5',
    'phi': u'\u03C6',
    'chi': u'\u03C7',
    'psi': u'\u03C8',
    'omega':  u'\u03C9'
}

greek_alphabet = {
    "Alpha": u"\u0391" ,
    "Beta": u"\u0392",
    "Gamma": u"\u0393",
    "Delta": u"\u0394",
    "Epsilon": u"\u0395",
    "Zeta": u"\u0396",
    "Eta": u"\u0397",
    "Theta": u"\u0398",
    "Iota": u"\u0399",
    "Kappa": u"\u039A",
    "Lamda": u"\u039B",
    "Mu": u"\u039C",
    "Nu": u"\u039D",
    "Xi": u"\u039E",
    "Omicron": u"\u039F",
    "Pi": u"\u03A0",
    "Rho": u"\u03A1",
    "Sigma": u"\u03A3",
    "Tau": u"\u03A4",
    "Upsilon": u"\u03A5",
    "Phi": u"\u03A6",
    "Chi": u"\u03A7",
    "Psi": u"\u03A8",
    "Omega": u"\u03A9",
}

greek_alphabet_lowercase = {
    "Alpha": u"\u03B1",
    "Beta": u"\u03B2",
    "Gamma": u"\u03B3",
    "Delta": u"\u03B4",
    "Epsilon": u"\u03B5",
    "Zeta": u"\u03B6",
    "Eta": u"\u03B7",
    "Theta": u"\u03B8",
    "Iota": u"\u03B9",
    "Kappa": u"\u03BA",
    "Lamda": u"\u03BB",
    "Mu": u"\u03BC",
    "Nu": u"\u03BD",
    "Xi": u"\u03BE",
    "Omicron": u"\u03BF",
    "Pi": u"\u03C0",
    "Rho": u"\u03C1",
    "Sigma": u"\u03C3",
    "Tau": u"\u03C4",
    "Upsilon": u"\u03C5",
    "Phi": u"\u03C6",
    "Chi": u"\u03C7",
    "Psi": u"\u03C8",
    "Omega":  u"\u03C9"
}

# if swe_id is lllUll then it is a Bayer designation
# where lll is a greek letter and Ull is a constellation abbreviation (for the Latin genitive)
# U(ll) is for other things, e.g., VC for Virgo Cluster, HIP for Hipparcos Catalogue number, etc.
# nnUll is a Flamsteed designation and will end up as ConstNN in Python
# e.g., ,48Lib becomes Librae48()
star_names_short_to_long = {
    "greek": {
        # note: simbad returns two-letter names with an additional "."
        # e.g., "mu.Sgr"
        # not all the letters of the greek alphabet
        # just those used in Bayer designations
        "alf": "Alpha",
        "bet": "Beta",
        "gam": "Gamma",
        # for one star that had some weird stuff happen to it
        "g": "Gamma",
        "del": "Delta",
        # for dOph -> d Ophiuci? just because?
        "d": "Delta",
        "eps": "Epsilon",
        "zet": "Zeta",
        "eta": "Eta", # but no stars with that letter
        "tet": "Theta",
        "iot": "Iota",
        "kap": "Kappa",
        "lam": "Lambda",
        "mu.": "Mu",
        "nu.": "Nu",
        "ksi": "Xi",
        "omi": "Omicron",
        # it seems simbad may use "pi." to have three letters?
        "pi.": "Pi",
        "rho": "Rho",
        "sig": "Sigma",
        "tau": "Tau",
        "ups": "Upsilon",
        "phi": "Phi",
        "chi": "Chi",
        "psi": "Psi",
        "ome": "Omega",
    },
    "constellations": {
        "Ari": "Arietis",
        "Tau": "Tauri",
        "Gem": "Geminorum",
        "Cnc": "Cancri",
        "Leo": "Leonis",
        "Vir": "Virginis",
        "Lib": "Librae",
        "Sco": "Scorpii",
        "Oph": "Ophiuci",
        "Sgr": "Sagittarii",
        "Cap": "Capricorni",
        "Aqr": "Aquarii",
        "And": "Andromedae",
        "Ant": "Antilae",
        "Aps": "Apodis", # Apus constellation
        "Ara": "Arae",
        "Psc": "Piscium",
        "Eri": "Eridani",
        "Cae": "Caeli",
        "Cam": "Camelopardalis",
        "Cas": "Cassiopeiae",
        "Cen": "Centauri",
        "Cep": "Cephei",
        "UMa": "Ursae Majoris",
        "UMi": "Ursae Minoris",
        "Aql": "Aquilae",
        "Hyd": "Hydrae",
        "Sct": "Scuti",
        "Sex": "Sextantis",
        "Sge": "Sagittae",
        "Boo": "Bootis",
        "Dra": "Draconis",
        "Del": "Delphini",
        "Dor": "Doradus",
        "Equ": "Equulei",
        "For": "Fornacis", # Fornax constellation
        "Cyg": "Cygni",
        "Gru": "Gruis",
        "Ori": "Orionis",
        "Cet": "Ceti",
        "Cha": "Chamaeleontis", # Chamaeleon constellation
        "Cir": "Circini", # Circinus constellation
        "Col": "Columbae",
        "Com": "Comae Berenices",
        "CrB": "Coronae Borealis",
        "CrA": "Coronae Australis",
        "TCrB": "TCoronae Borealis",
        "Crt": "Crateris",
        "Cru": "Crucis",
        "Crv": "Corvi",
        "CVn": "Canum Venaticorum",
        "CMa": "Canis Majoris",
        "CMi": "Canis Minors",
        "Aur": "Aurigae",
        "Car": "Carinae",
        "Lyr": "Lyrae",
        "Lep": "Leporis",
        "Men": "Mensae",
        "Mic": "Microscopii",
        "Mon": "Monocerotis",
        "Mus": "Muscae",
        "Nor": "Normae",
        "Oct": "Octantis",
        "Ind": "Indi",
        "Pav": "Pavonis",
        "Peg": "Pegasi",
        "Phe": "Phoenicis",
        "LMi": "Leonis Minoris",
        "Lup": "Lupi",
        "Lyn": "Lyncis",
        "Ser": "Serpentis",
        "Tel": "Telescopium",
        "TrA": "Trianguli Australis",
        "Tri": "Trianguli",
        "Tuc": "Tucanae",
        "Her": "Herculis",
        "Hor": "Horologii",
        "Hya": "Hydrae",
        "Hyi": "Hydri",
        "Lac": "Lacertae",
        "Per": "Persei",
        "Pic": "Pictoris",
        "PsA": "Piscis Austrini",
        "Pup": "Puppis",
        "Pyx": "Pyxis",
        "Ret": "Reticulum",
        "Scl": "Sculptoris",
        "Vel": "Velorum", # Vela, contains Vela supercluster
        "Vol": "Volantis",
        "Vul": "Vulpeculae",
        "VC": "Virgo Cluster",
        "M": "Messier Object",
        "NGC": "New General Catalogue",
        "HIP": "Hipparcos Catalogue",
        "HR": "Bright Star Catalogue",
        "HD": "Henry Draper Catalogue",
    }
}

bayer_nomen_lba_to_swe = {
    # also note that for new to old need to change 0 to "-"
    # e.g., del01Gru goes to de-1Gru

    # this is for converting 6-letter Bayer designations to 5-letter ones
    # to match with the original ephe/sefstars.txt sweph file
    "alf": "al",
    "bet": "be",
    "gam": "ga",
    # for one star that had some weird stuff happen to it
    "del": "de",
    "eps": "ep",
    "zet": "ze",
    "eta": "et", # but no stars with that letter
    "tet": "th",
    "iot": "io",
    "kap": "ka",
    "lam": "la",
    "mu.": "mu",
    "nu.": "nu",
    "ksi": "xi",
    "omi": "omi",
    "pi.": "pi",
    "rho": "rh",
    "sig": "si",
    "tau": "ta",
    "ups": "up",
    "phi": "ph",
    "chi": "ch",
    "psi": "ps",
    "ome": "ome",
}
